In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
URL = "https://www.worldometers.info/world-population/"

In [3]:
response = requests.get(URL)

In [4]:
soup = BeautifulSoup(response.text, 'html.parser')

In [5]:
tables = soup.find_all("table")
len(tables)

5

In [6]:
def tabel_scrap(table):
    return table.find_all("tr")

In [7]:
def rows_scrap(rows, scrapping="Columns Name"):
    if scrapping == "Columns Name":
        return [header.text.strip() for header in rows[0].find_all("th")]
    
    data = []
    for row in rows[1:]:
        cells = row.find_all("td")
        data.append([cell.text.strip() for cell in cells])
    return data

In [8]:
def create_df(data, columns):
    return pd.DataFrame(data, columns=columns)

In [9]:
table0 = tables[0]
table0_rows = tabel_scrap(table0)

In [10]:
table0_col_name = rows_scrap(table0_rows)
table0_col_name

['Year(July 1)',
 'Population',
 'Yearly %Change',
 'YearlyChange',
 'MedianAge',
 'FertilityRate',
 'Density(P/Km²)']

In [11]:
table0_data = rows_scrap(table0_rows, scrapping="data")
table0_data

[['2025', '8,231,613,070', '0.85%', '69,640,498', '30.9', '2.24', '55'],
 ['2024', '8,161,972,572', '0.87%', '70,237,642', '30.6', '2.25', '55'],
 ['2023', '8,091,734,930', '0.88%', '70,327,738', '30.4', '2.25', '54'],
 ['2022', '8,021,407,192', '0.84%', '66,958,801', '30.1', '2.27', '54'],
 ['2021', '7,954,448,391', '0.86%', '67,447,099', '29.8', '2.29', '53'],
 ['2020', '7,887,001,292', '1.09%', '83,301,884', '29.6', '2.32', '53'],
 ['2015', '7,470,491,872', '1.25%', '89,751,945', '28.3', '2.54', '50'],
 ['2010', '7,021,732,148', '1.29%', '86,952,403', '27.2', '2.6', '47'],
 ['2005', '6,586,970,132', '1.31%', '83,053,428', '26.1', '2.63', '44'],
 ['2000', '6,171,702,993', '1.39%', '82,564,802', '25.1', '2.75', '41'],
 ['1995', '5,758,878,982', '1.57%', '86,215,174', '24', '2.89', '39'],
 ['1990', '5,327,803,110', '1.82%', '91,771,929', '22.9', '3.31', '36'],
 ['1985', '4,868,943,465', '1.83%', '84,267,446', '22', '3.52', '33'],
 ['1980', '4,447,606,236', '1.79%', '75,374,192', '21.5', '3.74', '30'],
 ['1975', '4,070,735,277', '1.96%', '75,210,297', '20.7', '4.08', '27'],
 ['1970', '3,694,683,794', '2.07%', '72,030,018', '20.3', '4.83', '25'],
 ['1965', '3,334,533,703', '2.03%', '63,812,562', '20.8', '5.07', '22'],
 ['1960', '3,015,470,894', '1.93%', '55,051,420', '21.5', '4.7', '20'],
 ['1955', '2,740,213,792', '1.91%', '49,424,189', '21.8', '5', '18']]

In [12]:
world_population_history = create_df(table0_data, table0_col_name)
world_population_history

,Year(July 1),Population,Yearly %Change,YearlyChange,MedianAge,FertilityRate,Density(P/Km²)
0,2025,"8,231,613,070",0.85%,"69,640,498",30.9,2.24,55
1,2024,"8,161,972,572",0.87%,"70,237,642",30.6,2.25,55
2,2023,"8,091,734,930",0.88%,"70,327,738",30.4,2.25,54
3,2022,"8,021,407,192",0.84%,"66,958,801",30.1,2.27,54
4,2021,"7,954,448,391",0.86%,"67,447,099",29.8,2.29,53
5,2020,"7,887,001,292",1.09%,"83,301,884",29.6,2.32,53
6,2015,"7,470,491,872",1.25%,"89,751,945",28.3,2.54,50
7,2010,"7,021,732,148",1.29%,"86,952,403",27.2,2.6,47
8,2005,"6,586,970,132",1.31%,"83,053,428",26.1,2.63,44
9,2000,"6,171,702,993",1.39%,"82,564,802",25.1,2.75,41
10,1995,"5,758,878,982",1.57%,"86,215,174",24,2.89,39
11,1990,"5,327,803,110",1.82%,"91,771,929",22.9,3.31,36
12,1985,"4,868,943,465",1.83%,"84,267,446",22,3.52,33
13,1980,"4,447,606,236",1.79%,"75,374,192",21.5,3.74,30
14,1975,"4,070,735,277",1.96%,"75,210,297",20.7,4.08,27
15,1970,"3,694,683,794",2.07%,"72,030,018",20.3,4.83,25
16,1965,"3,334,533,703",2.03%,"63,812,562",20.8,5.07,22
17,1960,"3,015,470,894",1.93%,"55,051,420",21.5,4.7,20
18,1955,"2,740,213,792",1.91%,"49,424,189",21.8,5,18

In [13]:
table1 = tables[1]
table1_rows = tabel_scrap(table1)

In [14]:
table1_col_name = rows_scrap(table1_rows)
table1_col_name

['Year(July 1)',
 'Population',
 'Yearly %Change',
 'YearlyChange',
 'MedianAge',
 'FertilityRate',
 'Density(P/Km²)']

In [15]:
table1_data = rows_scrap(table1_rows, scrapping="data")
table1_data

[['2030', '8,569,124,911', '0.81%', '67,502,368', '32', '2.2', '58'],
 ['2035', '8,885,210,181', '0.73%', '63,217,054', '33', '2.15', '60'],
 ['2040', '9,177,190,203', '0.65%', '58,396,004', '34', '2.13', '62'],
 ['2045', '9,439,639,668', '0.57%', '52,489,893', '35', '2.12', '63'],
 ['2050', '9,664,378,587', '0.47%', '44,947,784', '36.1', '2.1', '65']]

In [16]:
world_population_forecast = create_df(table1_data, table1_col_name)
world_population_forecast

,Year(July 1),Population,Yearly %Change,YearlyChange,MedianAge,FertilityRate,Density(P/Km²)
0,2030,"8,569,124,911",0.81%,"67,502,368",32,2.2,58
1,2035,"8,885,210,181",0.73%,"63,217,054",33,2.15,60
2,2040,"9,177,190,203",0.65%,"58,396,004",34,2.13,62
3,2045,"9,439,639,668",0.57%,"52,489,893",35,2.12,63
4,2050,"9,664,378,587",0.47%,"44,947,784",36.1,2.1,65

In [17]:
table2 = tables[2]
table2_rows = tabel_scrap(table2)

In [18]:
table2_col_name = rows_scrap(table2_rows)
table2_col_name

['Year',
 '1',
 '1000',
 '1500',
 '1650',
 '1750',
 '1804',
 '1850',
 '1900',
 '1930',
 '1950',
 '1960',
 '1974',
 '1980',
 '1987',
 '1998',
 '2010',
 '2022',
 '2029',
 '2037',
 '2046',
 '2060',
 '2100']

In [19]:
table2_data = rows_scrap(table2_rows, scrapping="data")
table2_data

[['Population',
  '0.2',
  '0.275',
  '0.45',
  '0.5',
  '0.7',
  '1',
  '1.2',
  '1.6',
  '2',
  '2.55',
  '3',
  '4',
  '4.5',
  '5',
  '6',
  '7',
  '8',
  '8.5',
  '9',
  '9.5',
  '10',
  '10.2']]

In [20]:
sumary_table = create_df(table2_data, table2_col_name)
sumary_table

,Year,1,1000,1500,1650,1750,1804,1850,1900,1930,...,1980,1987,1998,2010,2022,2029,2037,2046,2060,2100
0,Population,0.2,0.275,0.45,0.5,0.7,1,1.2,1.6,2,...,4.5,5,6,7,8,8.5,9,9.5,10,10.2

In [21]:
table3 = tables[3]
table3_rows = tabel_scrap(table3)

In [22]:
table3_col_name = rows_scrap(table3_rows)
table3_col_name

['#',
 'Region',
 'Population(2025)',
 'YearlyChange',
 'NetChange',
 'Density(P/Km²)',
 'Land Area(Km²)',
 'Migrants(net)',
 'Fert.Rate',
 'MedianAge',
 'UrbanPop %',
 'WorldShare']

In [23]:
table3_data = rows_scrap(table3_rows, scrapping="data")
table3_data

[['1',
  'Asia',
  '4,835,320,060',
  '0.59%',
  '28,422,053',
  '156',
  '31,033,131',
  '−2,389,647',
  '1.87',
  '32.5',
  '53.6%',
  '58.74%'],
 ['2',
  'Africa',
  '1,549,867,579',
  '2.29%',
  '34,726,730',
  '52',
  '29,648,481',
  '−377,785',
  '3.95',
  '19.3',
  '45%',
  '18.83%'],
 ['3',
  'Europe',
  '744,398,832',
  '−0.09%',
  '−684,992',
  '34',
  '22,134,900',
  '1,478,090',
  '1.41',
  '42.8',
  '75.9%',
  '9.04%'],
 ['4',
  'Latin America and the Caribbean',
  '667,888,552',
  '0.67%',
  '4,422,480',
  '33',
  '20,139,378',
  '−406,036',
  '1.78',
  '31.7',
  '85.5%',
  '8.11%'],
 ['5',
  'Northern America',
  '387,528,403',
  '0.58%',
  '2,233,298',
  '21',
  '18,651,660',
  '1,556,592',
  '1.59',
  '38.7',
  '82.5%',
  '4.71%'],
 ['6',
  'Oceania',
  '46,609,644',
  '1.13%',
  '520,928',
  '5',
  '8,486,460',
  '140,121',
  '2.13',
  '33.4',
  '66.2%',
  '0.57%']]

In [24]:
world_population_Region = create_df(table3_data, table3_col_name)
world_population_Region.drop('#', inplace=True, axis=1)
world_population_Region

,Region,Population(2025),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,MedianAge,UrbanPop %,WorldShare
0,Asia,"4,835,320,060",0.59%,"28,422,053",156,"31,033,131","−2,389,647",1.87,32.5,53.6%,58.74%
1,Africa,"1,549,867,579",2.29%,"34,726,730",52,"29,648,481","−377,785",3.95,19.3,45%,18.83%
2,Europe,"744,398,832",−0.09%,"−684,992",34,"22,134,900","1,478,090",1.41,42.8,75.9%,9.04%
3,Latin America and the Caribbean,"667,888,552",0.67%,"4,422,480",33,"20,139,378","−406,036",1.78,31.7,85.5%,8.11%
4,Northern America,"387,528,403",0.58%,"2,233,298",21,"18,651,660","1,556,592",1.59,38.7,82.5%,4.71%
5,Oceania,"46,609,644",1.13%,"520,928",5,"8,486,460","140,121",2.13,33.4,66.2%,0.57%

In [25]:
table4 = tables[4]
table4_rows = tabel_scrap(table4)

In [26]:
table4_col_name = rows_scrap(table4_rows)
table4_col_name

['#',
 'Country (ordependency)',
 'Population(2025)',
 'YearlyChange',
 'NetChange',
 'Density(P/Km²)',
 'Land Area(Km²)',
 'Migrants(net)',
 'Fert.Rate',
 'MedianAge',
 'UrbanPop %',
 'WorldShare']

In [27]:
table4_data = rows_scrap(table4_rows, scrapping="data")
table4_data

[['1',
  'India',
  '1,463,865,525',
  '0.89%',
  '12,929,734',
  '492',
  '2,973,190',
  '−495,753',
  '1.94',
  '28.8',
  '37.1%',
  '17.78%'],
 ['2',
  'China',
  '1,416,096,094',
  '−0.23%',
  '−3,225,184',
  '151',
  '9,388,211',
  '−268,126',
  '1.02',
  '40.1',
  '67.5%',
  '17.20%'],
 ['3',
  'United States',
  '347,275,807',
  '0.54%',
  '1,849,236',
  '38',
  '9,147,420',
  '1,230,663',
  '1.62',
  '38.5',
  '82.8%',
  '4.22%'],
 ['4',
  'Indonesia',
  '285,721,236',
  '0.79%',
  '2,233,305',
  '158',
  '1,811,570',
  '−39,509',
  '2.1',
  '30.4',
  '59.6%',
  '3.47%'],
 ['5',
  'Pakistan',
  '255,219,554',
  '1.57%',
  '3,950,390',
  '331',
  '770,880',
  '−1,235,336',
  '3.5',
  '20.6',
  '34.4%',
  '3.10%'],
 ['6',
  'Nigeria',
  '237,527,782',
  '2.08%',
  '4,848,304',
  '261',
  '910,770',
  '−15,258',
  '4.3',
  '18.1',
  '54.9%',
  '2.89%'],
 ['7',
  'Brazil',
  '212,812,405',
  '0.38%',
  '813,832',
  '25',
  '8,358,140',
  '−217,283',
  '1.6',
  '34.8',
  '91.4%',
  '2.59%'],
 ['8',
  'Bangladesh',
  '175,686,899',
  '1.22%',
  '2,124,535',
  '1,350',
  '130,170',
  '−402,100',
  '2.11',
  '26',
  '42.6%',
  '2.13%'],
 ['9',
  'Russia',
  '143,997,393',
  '−0.57%',
  '−823,030',
  '9',
  '16,376,870',
  '−251,822',
  '1.47',
  '40.3',
  '75%',
  '1.75%'],
 ['10',
  'Ethiopia',
  '135,472,051',
  '2.58%',
  '3,412,284',
  '135',
  '1,000,000',
  '24,054',
  '3.81',
  '19.1',
  '22.5%',
  '1.65%'],
 ['11',
  'Mexico',
  '131,946,900',
  '0.83%',
  '1,085,893',
  '68',
  '1,943,950',
  '−108,037',
  '1.87',
  '29.6',
  '87.9%',
  '1.60%'],
 ['12',
  'Japan',
  '123,103,479',
  '−0.52%',
  '−649,562',
  '338',
  '364,555',
  '140,579',
  '1.23',
  '49.8',
  '93.1%',
  '1.50%'],
 ['13',
  'Egypt',
  '118,365,995',
  '1.57%',
  '1,827,737',
  '119',
  '995,450',
  '−57,305',
  '2.71',
  '24.5',
  '40.9%',
  '1.44%'],
 ['14',
  'Philippines',
  '116,786,962',
  '0.81%',
  '943,292',
  '392',
  '298,170',
  '−149,315',
  '1.88',
  '26.1',
  '49.3%',
  '1.42%'],
 ['15',
  'DR Congo',
  '112,832,473',
  '3.25%',
  '3,556,208',
  '50',
  '2,267,050',
  '−27,309',
  '5.9',
  '15.8',
  '45%',
  '1.37%'],
 ['16',
  'Vietnam',
  '101,598,527',
  '0.6%',
  '610,841',
  '328',
  '310,070',
  '−48,171',
  '1.88',
  '33.4',
  '41.4%',
  '1.23%'],
 ['17',
  'Iran',
  '92,417,681',
  '0.93%',
  '849,943',
  '57',
  '1,628,550',
  '116,786',
  '1.67',
  '34',
  '73.3%',
  '1.12%'],
 ['18',
  'Turkey',
  '87,685,426',
  '0.24%',
  '211,621',
  '114',
  '769,630',
  '−258,205',
  '1.62',
  '33.5',
  '76.9%',
  '1.07%'],
 ['19',
  'Germany',
  '84,075,075',
  '−0.56%',
  '−477,167',
  '241',
  '348,560',
  '−334,072',
  '1.46',
  '45.5',
  '76.5%',
  '1.02%'],
 ['20',
  'Thailand',
  '71,619,863',
  '−0.07%',
  '−48,148',
  '140',
  '510,890',
  '27,509',
  '1.2',
  '40.6',
  '53.5%',
  '0.87%'],
 ['21',
  'Tanzania',
  '70,545,865',
  '2.9%',
  '1,985,708',
  '80',
  '885,800',
  '−12,730',
  '4.47',
  '17.5',
  '40%',
  '0.86%'],
 ['22',
  'United Kingdom',
  '69,551,332',
  '0.6%',
  '413,140',
  '287',
  '241,930',
  '389,911',
  '1.54',
  '40.1',
  '84.5%',
  '0.84%'],
 ['23',
  'France',
  '66,650,804',
  '0.15%',
  '102,274',
  '122',
  '547,557',
  '91,737',
  '1.64',
  '42.3',
  '82.5%',
  '0.81%'],
 ['24',
  'South Africa',
  '64,747,319',
  '1.16%',
  '740,132',
  '53',
  '1,213,090',
  '146,370',
  '2.19',
  '28.7',
  '66.6%',
  '0.79%'],
 ['25',
  'Italy',
  '59,146,260',
  '−0.33%',
  '−196,607',
  '201',
  '294,140',
  '75,448',
  '1.21',
  '48.2',
  '72%',
  '0.72%'],
 ['26',
  'Kenya',
  '57,532,493',
  '1.95%',
  '1,099,549',
  '101',
  '569,140',
  '−27,330',
  '3.12',
  '20',
  '31.9%',
  '0.70%'],
 ['27',
  'Myanmar',
  '54,850,648',
  '0.64%',
  '350,557',
  '84',
  '653,290',
  '−39,661',
  '2.08',
  '30.1',
  '34.1%',
  '0.67%'],
 ['28',
  'Colombia',
  '53,425,635',
  '1.02%',
  '539,272',
  '48',
  '1,109,500',
  '129,139',
  '1.62',
  '32.5',
  '80.5%',
  '0.65%'],
 ['29',
  'South Korea',
  '51,667,029',
  '−0.1%',
  '−50,561',
  '531',
  '97,230',
  '65,731',
  '0.75',
  '45.6',
  '82.4%',
  '0.63%'],
 ['30',
  'Sudan',
  '51,662,147',
  '2.4%',
  '1,213,184',
  '29',
  '1,765,048',
  '291,469',
  '4.19',
  '18.5',
  '35.3%',
  '0.63%'],
 ['31',
  'Uganda',
  '51,384,894',
  '2.74%',
  '1,369,802',
  '257',
  '199,810',
  '−119,059',
  '4.06',
  '16.9',
  '30%',
  '0.62%'],
 ['32',
  'Spain',
  '47,889,958',
  '−0.04%',
  '−20,568',
  '96',
  '498,800',
  '96,630',
  '1.23',
  '45.9',
  '79.3%',
  '0.58%'],
 ['33',
  'Algeria',
  '47,435,312',
  '1.33%',
  '621,004',
  '20',
  '2,381,740',
  '−27,531',
  '2.67',
  '28.6',
  '74.4%',
  '0.58%'],
 ['34',
  'Iraq',
  '47,020,774',
  '2.13%',
  '978,759',
  '108',
  '434,320',
  '−1,064',
  '3.17',
  '20.8',
  '72.4%',
  '0.57%'],
 ['35',
  'Argentina',
  '45,851,378',
  '0.34%',
  '155,219',
  '17',
  '2,736,690',
  '2,859',
  '1.5',
  '32.9',
  '96%',
  '0.56%'],
 ['36',
  'Afghanistan',
  '43,844,111',
  '2.81%',
  '1,196,619',
  '67',
  '652,860',
  '−74,404',
  '4.66',
  '17.3',
  '26.7%',
  '0.53%'],
 ['37',
  'Yemen',
  '41,773,878',
  '2.93%',
  '1,190,714',
  '79',
  '527,970',
  '−16,291',
  '4.41',
  '18.4',
  '33%',
  '0.51%'],
 ['38',
  'Canada',
  '40,126,723',
  '0.97%',
  '384,293',
  '4',
  '9,093,510',
  '326,204',
  '1.33',
  '40.6',
  '80.2%',
  '0.49%'],
 ['39',
  'Angola',
  '39,040,039',
  '3.05%',
  '1,154,190',
  '31',
  '1,246,700',
  '−3,524',
  '4.95',
  '16.6',
  '68.8%',
  '0.47%'],
 ['40',
  'Ukraine',
  '38,980,376',
  '2.96%',
  '1,120,155',
  '67',
  '579,320',
  '1,702,358',
  '1',
  '41.8',
  '76.8%',
  '0.47%'],
 ['41',
  'Morocco',
  '38,430,770',
  '0.92%',
  '349,597',
  '86',
  '446,300',
  '−56,254',
  '2.18',
  '29.8',
  '67.3%',
  '0.47%'],
 ['42',
  'Poland',
  '38,140,910',
  '−1.03%',
  '−398,291',
  '125',
  '306,230',
  '−330,820',
  '1.31',
  '42.5',
  '59.2%',
  '0.46%'],
 ['43',
  'Uzbekistan',
  '37,053,428',
  '1.9%',
  '691,569',
  '87',
  '425,400',
  '−6,987',
  '3.45',
  '27',
  '48.1%',
  '0.45%'],
 ['44',
  'Malaysia',
  '35,977,838',
  '1.18%',
  '420,165',
  '110',
  '328,550',
  '166,615',
  '1.53',
  '31',
  '77.4%',
  '0.44%'],
 ['45',
  'Mozambique',
  '35,631,653',
  '2.89%',
  '999,887',
  '45',
  '786,380',
  '−65,573',
  '4.62',
  '16.5',
  '41.6%',
  '0.43%'],
 ['46',
  'Ghana',
  '35,064,272',
  '1.85%',
  '636,858',
  '154',
  '227,540',
  '−17,079',
  '3.3',
  '21.3',
  '58.6%',
  '0.43%'],
 ['47',
  'Peru',
  '34,576,665',
  '1.05%',
  '358,817',
  '27',
  '1,280,000',
  '11,931',
  '1.94',
  '30.2',
  '80.6%',
  '0.42%'],
 ['48',
  'Saudi Arabia',
  '34,566,328',
  '1.78%',
  '603,571',
  '16',
  '2,149,690',
  '119,738',
  '2.29',
  '29.6',
  '92.1%',
  '0.42%'],
 ['49',
  'Madagascar',
  '32,740,678',
  '2.43%',
  '775,722',
  '56',
  '581,795',
  '−2,227',
  '3.85',
  '19.2',
  '40.3%',
  '0.40%'],
 ['50',
  "Côte d'Ivoire",
  '32,711,547',
  '2.43%',
  '777,317',
  '103',
  '318,000',
  '11,305',
  '4.17',
  '18.3',
  '49%',
  '0.40%'],
 ['51',
  'Cameroon',
  '29,879,337',
  '2.59%',
  '755,593',
  '63',
  '472,710',
  '−15,379',
  '4.18',
  '18',
  '59.4%',
  '0.36%'],
 ['52',
  'Nepal',
  '29,618,118',
  '−0.11%',
  '−32,936',
  '207',
  '143,350',
  '−364,699',
  '1.94',
  '25.3',
  '24.5%',
  '0.36%'],
 ['53',
  'Venezuela',
  '28,516,896',
  '0.39%',
  '111,353',
  '32',
  '882,050',
  '−100,467',
  '2.06',
  '29.4',
  '',
  '0.35%'],
 ['54',
  'Niger',
  '27,917,831',
  '3.28%',
  '885,419',
  '22',
  '1,266,700',
  '−7,704',
  '5.79',
  '15.6',
  '18.2%',
  '0.34%'],
 ['55',
  'Australia',
  '26,974,026',
  '0.98%',
  '260,821',
  '4',
  '7,682,300',
  '137,109',
  '1.64',
  '38.3',
  '86.5%',
  '0.33%'],
 ['56',
  'North Korea',
  '26,571,036',
  '0.27%',
  '72,213',
  '221',
  '120,410',
  '−2,787',
  '1.77',
  '36.5',
  '63.3%',
  '0.32%'],
 ['57',
  'Syria',
  '25,620,427',
  '3.84%',
  '947,667',
  '140',
  '183,630',
  '421,693',
  '2.66',
  '23.3',
  '53.6%',
  '0.31%'],
 ['58',
  'Mali',
  '25,198,821',
  '2.94%',
  '720,226',
  '21',
  '1,220,190',
  '−48,019',
  '5.42',
  '15.7',
  '44.4%',
  '0.31%'],
 ['59',
  'Burkina Faso',
  '24,074,580',
  '2.23%',
  '525,799',
  '88',
  '273,600',
  '−27,130',
  '4',
  '17.7',
  '33.7%',
  '0.29%'],
 ['60',
  'Sri Lanka',
  '23,229,470',
  '0.54%',
  '125,905',
  '370',
  '62,710',
  '−30,724',
  '1.94',
  '33.3',
  '18.1%',
  '0.28%'],
 ['61',
  'Taiwan',
  '23,112,793',
  '−0.44%',
  '−101,169',
  '653',
  '35,410',
  '−20,947',
  '0.86',
  '44.8',
  '84%',
  '0.28%'],
 ['62',
  'Malawi',
  '22,216,120',
  '2.59%',
  '560,834',
  '236',
  '94,280',
  '−5,628',
  '3.53',
  '18.1',
  '19.8%',
  '0.27%'],
 ['63',
  'Zambia',
  '21,913,874',
  '2.81%',
  '598,918',
  '29',
  '743,390',
  '6,562',
  '3.97',
  '17.9',
  '46.8%',
  '0.27%'],
 ['64',
  'Chad',
  '21,003,705',
  '3.47%',
  '704,582',
  '17',
  '1,259,200',
  '−123,104',
  '5.94',
  '15.8',
  '22.4%',
  '0.26%'],
 ['65',
  'Kazakhstan',
  '20,843,754',
  '1.22%',
  '251,183',
  '8',
  '2,699,700',
  '−8,834',
  '2.95',
  '29.7',
  '55.1%',
  '0.25%'],
 ['66',
  'Chile',
  '19,859,921',
  '0.48%',
  '95,150',
  '27',
  '743,532',
  '51,712',
  '1.13',
  '36.9',
  '84.8%',
  '0.24%'],
 ['67',
  'Somalia',
  '19,654,739',
  '3.4%',
  '645,588',
  '31',
  '627,340',
  '12,077',
  '5.91',
  '15.6',
  '46.6%',
  '0.24%'],
 ['68',
  'Senegal',
  '18,931,966',
  '2.32%',
  '429,982',
  '98',
  '192,530',
  '−12,636',
  '3.71',
  '19.6',
  '52.3%',
  '0.23%'],
 ['69',
  'Romania',
  '18,908,650',
  '−0.56%',
  '−106,438',
  '82',
  '230,170',
  '−29,041',
  '1.71',
  '43.2',
  '55.2%',
  '0.23%'],
 ['70',
  'Guatemala',
  '18,687,881',
  '1.53%',
  '281,522',
  '174',
  '107,160',
  '−7,959',
  '2.26',
  '23.4',
  '56.6%',
  '0.23%'],
 ['71',
  'Netherlands',
  '18,346,819',
  '0.65%',
  '118,077',
  '544',
  '33,720',
  '104,681',
  '1.44',
  '41.5',
  '88.9%',
  '0.22%'],
 ['72',
  'Ecuador',
  '18,289,896',
  '0.85%',
  '154,418',
  '74',
  '248,360',
  '−17,219',
  '1.79',
  '29.3',
  '66%',
  '0.22%'],
 ['73',
  'Cambodia',
  '17,847,982',
  '1.19%',
  '209,181',
  '101',
  '176,520',
  '−31,469',
  '2.51',
  '26.2',
  '26.5%',
  '0.22%'],
 ['74',
  'Zimbabwe',
  '16,950,795',
  '1.9%',
  '316,422',
  '44',
  '386,850',
  '−54,555',
  '3.62',
  '18.1',
  '37.9%',
  '0.21%'],
 ['75',
  'Guinea',
  '15,099,727',
  '2.34%',
  '344,942',
  '61',
  '245,720',
  '−16,282',
  '4.04',
  '18.3',
  '40.3%',
  '0.18%'],
 ['76',
  'Benin',
  '14,814,460',
  '2.43%',
  '351,736',
  '131',
  '112,760',
  '−7,847',
  '4.42',
  '18',
  '47.8%',
  '0.18%'],
 ['77',
  'Rwanda',
  '14,569,341',
  '2.19%',
  '312,774',
  '591',
  '24,670',
  '6,282',
  '3.59',
  '19.9',
  '18.3%',
  '0.18%'],
 ['78',
  'Burundi',
  '14,390,003',
  '2.44%',
  '342,217',
  '560',
  '25,680',
  '−34,727',
  '4.67',
  '16.4',
  '14.9%',
  '0.17%'],
 ['79',
  'Bolivia',
  '12,581,843',
  '1.36%',
  '168,528',
  '12',
  '1,083,300',
  '−3,179',
  '2.5',
  '25.2',
  '70.6%',
  '0.15%'],
 ['80',
  'Tunisia',
  '12,348,573',
  '0.58%',
  '71,464',
  '79',
  '155,360',
  '−14,523',
  '1.8',
  '32.9',
  '71.7%',
  '0.15%'],
 ['81',
  'South Sudan',
  '12,188,788',
  '2.05%',
  '245,380',
  '20',
  '610,952',
  '6,145',
  '3.71',
  '18.7',
  '27.7%',
  '0.15%'],
 ['82',
  'Haiti',
  '11,906,095',
  '1.13%',
  '133,538',
  '432',
  '27,560',
  '−32,052',
  '2.59',
  '24.1',
  '61.7%',
  '0.14%'],
 ['83',
  'Belgium',
  '11,758,603',
  '0.17%',
  '19,840',
  '388',
  '30,280',
  '31,989',
  '1.39',
  '41.9',
  '98.8%',
  '0.14%'],
 ['84',
  'Jordan',
  '11,520,684',
  '−0.28%',
  '−32,192',
  '130',
  '88,780',
  '−303,267',
  '2.57',
  '24.7',
  '85.1%',
  '0.14%'],
 ['85',
  'Dominican Republic',
  '11,520,487',
  '0.81%',
  '92,930',
  '238',
  '48,320',
  '−35,306',
  '2.19',
  '28.3',
  '86.4%',
  '0.14%'],
 ['86',
  'United Arab Emirates',
  '11,346,000',
  '2.89%',
  '318,871',
  '136',
  '83,600',
  '158,634',
  '1.21',
  '31.6',
  '81.1%',
  '0.14%'],
 ['87',
  'Honduras',
  '11,005,850',
  '1.66%',
  '180,147',
  '98',
  '111,890',
  '−4,778',
  '2.45',
  '24.2',
  '58.3%',
  '0.13%'],
 ['88',
  'Cuba',
  '10,937,203',
  '−0.39%',
  '−42,580',
  '103',
  '106,440',
  '−22,244',
  '1.45',
  '42.2',
  '81.9%',
  '0.13%'],
 ['89',
  'Tajikistan',
  '10,786,734',
  '1.85%',
  '195,807',
  '77',
  '139,960',
  '−21,606',
  '2.99',
  '22.2',
  '27.7%',
  '0.13%'],
 ['90',
  'Papua New Guinea',
  '10,762,817',
  '1.76%',
  '186,315',
  '24',
  '452,860',
  '−284',
  '3.03',
  '22.8',
  '12.6%',
  '0.13%'],
 ['91',
  'Sweden',
  '10,656,633',
  '0.47%',
  '49,634',
  '26',
  '410,340',
  '47,079',
  '1.44',
  '40.3',
  '87.4%',
  '0.13%'],
 ['92',
  'Czech Republic (Czechia)',
  '10,609,239',
  '−1.18%',
  '−126,620',
  '137',
  '77,240',
  '−112,188',
  '1.47',
  '43.8',
  '75%',
  '0.13%'],
 ['93',
  'Portugal',
  '10,411,834',
  '−0.13%',
  '−13,458',
  '114',
  '91,590',
  '16,472',
  '1.52',
  '46.9',
  '66.5%',
  '0.13%'],
 ['94',
  'Azerbaijan',
  '10,397,713',
  '0.59%',
  '61,136',
  '126',
  '82,658',
  '8,731',
  '1.67',
  '33.6',
  '58.7%',
  '0.13%'],
 ['95',
  'Greece',
  '9,938,844',
  '−1.08%',
  '−108,973',
  '77',
  '128,900',
  '16,636',
  '1.34',
  '46.8',
  '89.5%',
  '0.12%'],
 ['96',
  'Togo',
  '9,721,608',
  '2.17%',
  '206,372',
  '179',
  '54,390',
  '−15,010',
  '4.07',
  '19.1',
  '44.2%',
  '0.12%'],
 ['97',
  'Hungary',
  '9,632,287',
  '−0.45%',
  '−43,848',
  '106',
  '90,530',
  '−16,331',
  '1.5',
  '43.9',
  '72%',
  '0.12%'],
 ['98',
  'Israel',
  '9,517,181',
  '1.39%',
  '130,160',
  '440',
  '21,640',
  '11,466',
  '2.75',
  '29.2',
  '91.4%',
  '0.12%'],
 ['99',
  'Austria',
  '9,113,574',
  '−0.08%',
  '−7,239',
  '111',
  '82,409',
  '11,254',
  '1.33',
  '43.6',
  '58.6%',
  '0.11%'],
 ['100',
  'Belarus',
  '8,997,603',
  '−0.65%',
  '−59,093',
  '44',
  '202,910',
  '−3,020',
  '1.23',
  '41.3',
  '84.4%',
  '0.11%'],
 ['101',
  'Switzerland',
  '8,967,407',
  '0.51%',
  '45,426',
  '227',
  '39,516',
  '37,253',
  '1.44',
  '42.9',
  '74.4%',
  '0.11%'],
 ['102',
  'Sierra Leone',
  '8,819,794',
  '2.06%',
  '177,772',
  '122',
  '72,180',
  '−11,309',
  '3.61',
  '19.7',
  '45.5%',
  '0.11%'],
 ['103',
  'Laos',
  '7,873,046',
  '1.33%',
  '103,227',
  '34',
  '230,800',
  '−10,645',
  '2.36',
  '24.9',
  '38.3%',
  '0.096%'],
 ['104',
  'Turkmenistan',
  '7,618,847',
  '1.66%',
  '124,349',
  '16',
  '469,930',
  '13,268',
  '2.63',
  '26.9',
  '46.5%',
  '0.093%'],
 ['105',
  'Libya',
  '7,458,555',
  '1.05%',
  '77,532',
  '4',
  '1,759,540',
  '−172',
  '2.25',
  '27.7',
  '77.5%',
  '0.091%'],
 ['106',
  'Hong Kong',
  '7,396,076',
  '−0.25%',
  '−18,833',
  '7,044',
  '1,050',
  '17,863',
  '0.73',
  '47.4',
  '',
  '0.090%'],
 ['107',
  'Kyrgyzstan',
  '7,295,034',
  '1.52%',
  '109,025',
  '38',
  '191,800',
  '1,815',
  '2.75',
  '25.4',
  '35.3%',
  '0.089%'],
 ['108',
  'Paraguay',
  '7,013,078',
  '1.21%',
  '83,925',
  '18',
  '397,300',
  '−12,423',
  '2.4',
  '27',
  '68%',
  '0.085%'],
 ['109',
  'Nicaragua',
  '7,007,502',
  '1.32%',
  '91,362',
  '58',
  '120,340',
  '−8,371',
  '2.18',
  '26',
  '58.1%',
  '0.085%'],
 ['110',
  'Bulgaria',
  '6,714,560',
  '−0.64%',
  '−43,129',
  '62',
  '108,560',
  '−2,961',
  '1.74',
  '44.8',
  '77.1%',
  '0.082%'],
 ['111',
  'Serbia',
  '6,689,039',
  '−0.7%',
  '−47,177',
  '76',
  '87,460',
  '−13,086',
  '1.5',
  '44.4',
  '73.6%',
  '0.081%'],
 ['112',
  'Congo',
  '6,484,437',
  '2.39%',
  '151,476',
  '19',
  '341,500',
  '−2,999',
  '4.05',
  '18.6',
  '69.8%',
  '0.079%'],
 ['113',
  'El Salvador',
  '6,365,503',
  '0.43%',
  '27,310',
  '307',
  '20,720',
  '−23,934',
  '1.75',
  '27.9',
  '79.9%',
  '0.077%'],
 ['114',
  'Denmark',
  '6,002,507',
  '0.42%',
  '25,095',
  '141',
  '42,430',
  '22,103',
  '1.52',
  '41.3',
  '87.4%',
  '0.073%'],
 ['115',
  'Singapore',
  '5,870,750',
  '0.66%',
  '38,363',
  '8,387',
  '700',
  '16,892',
  '0.96',
  '36.2',
  '',
  '0.071%'],
 ['116',
  'Lebanon',
  '5,849,421',
  '0.75%',
  '43,459',
  '572',
  '10,230',
  '−10,230',
  '2.21',
  '28.8',
  '86%',
  '0.071%'],
 ['117',
  'Liberia',
  '5,731,206',
  '2.11%',
  '118,389',
  '60',
  '96,320',
  '−9,870',
  '3.79',
  '18.8',
  '55%',
  '0.070%'],
 ['118',
  'Finland',
  '5,623,329',
  '0.11%',
  '6,019',
  '19',
  '303,890',
  '18,246',
  '1.3',
  '43.2',
  '86.7%',
  '0.068%'],
 ['119',
  'Norway',
  '5,623,071',
  '0.83%',
  '46,411',
  '15',
  '365,268',
  '29,798',
  '1.42',
  '39.8',
  '85.9%',
  '0.068%'],
 ['120',
  'State of Palestine',
  '5,589,623',
  '1.71%',
  '94,180',
  '929',
  '6,020',
  '−23,156',
  '3.19',
  '20.1',
  '84.2%',
  '0.068%'],
 ['121',
  'Central African Republic',
  '5,513,282',
  '3.43%',
  '182,592',
  '9',
  '622,980',
  '−14,693',
  '5.81',
  '14.5',
  '44.5%',
  '0.067%'],
 ['122',
  'Oman',
  '5,494,691',
  '4.04%',
  '213,153',
  '18',
  '309,500',
  '113,734',
  '2.48',
  '29.7',
  '90.8%',
  '0.067%'],
 ['123',
  'Slovakia',
  '5,474,881',
  '−0.58%',
  '−31,879',
  '114',
  '48,088',
  '−31,377',
  '1.57',
  '42.3',
  '54%',
  '0.067%'],
 ['124',
  'Mauritania',
  '5,315,065',
  '2.82%',
  '145,670',
  '5',
  '1,030,700',
  '−5,044',
  '4.56',
  '17.4',
  '60.3%',
  '0.065%'],
 ['125',
  'Ireland',
  '5,308,039',
  '1.01%',
  '53,022',
  '77',
  '68,890',
  '35,417',
  '1.6',
  '39',
  '62.1%',
  '0.064%'],
 ['126',
  'New Zealand',
  '5,251,899',
  '0.73%',
  '37,955',
  '20',
  '263,310',
  '17,403',
  '1.65',
  '37.7',
  '83.6%',
  '0.064%'],
 ['127',
  'Costa Rica',
  '5,152,950',
  '0.45%',
  '23,040',
  '101',
  '51,060',
  '1,000',
  '1.31',
  '35.2',
  '85.2%',
  '0.063%'],
 ['128',
  'Kuwait',
  '5,026,078',
  '1.86%',
  '91,571',
  '282',
  '17,820',
  '42,775',
  '1.5',
  '34.8',
  '91.6%',
  '0.061%'],
 ['129',
  'Panama',
  '4,571,189',
  '1.23%',
  '55,612',
  '61',
  '74,340',
  '6,151',
  '2.09',
  '30.3',
  '70.7%',
  '0.056%'],
 ['130',
  'Croatia',
  '3,848,160',
  '−0.7%',
  '−27,165',
  '69',
  '55,960',
  '−3,481',
  '1.47',
  '45.3',
  '61.7%',
  '0.047%'],
 ['131',
  'Georgia',
  '3,806,671',
  '−0.03%',
  '−999',
  '55',
  '69,490',
  '1,283',
  '1.79',
  '37.3',
  '62%',
  '0.046%'],
 ['132',
  'Eritrea',
  '3,607,003',
  '2.02%',
  '71,400',
  '36',
  '101,000',
  '−6,698',
  '3.61',
  '19.2',
  '74.8%',
  '0.044%'],
 ['133',
  'Mongolia',
  '3,517,100',
  '1.2%',
  '41,560',
  '2',
  '1,553,560',
  '79',
  '2.58',
  '26.9',
  '67.2%',
  '0.043%'],
 ['134',
  'Uruguay',
  '3,384,688',
  '−0.06%',
  '−1,900',
  '19',
  '175,020',
  '−1,338',
  '1.39',
  '36.4',
  '',
  '0.041%'],
 ['135',
  'Puerto Rico',
  '3,235,289',
  '−0.21%',
  '−6,915',
  '365',
  '8,870',
  '5,495',
  '0.94',
  '45.8',
  '',
  '0.039%'],
 ['136',
  'Bosnia and Herzegovina',
  '3,140,095',
  '−0.76%',
  '−24,158',
  '62',
  '51,000',
  '−6,994',
  '1.5',
  '45.7',
  '56.3%',
  '0.038%'],
 ['137',
  'Qatar',
  '3,115,889',
  '2.21%',
  '67,466',
  '268',
  '11,610',
  '36,288',
  '1.7',
  '33.5',
  '96.6%',
  '0.038%'],
 ['138',
  'Namibia',
  '3,092,816',
  '2.07%',
  '62,685',
  '4',
  '823,290',
  '1,866',
  '3.17',
  '21.3',
  '54.4%',
  '0.038%'],
 ['139',
  'Moldova',
  '2,996,106',
  '−1.28%',
  '−38,855',
  '91',
  '32,850',
  '−29,766',
  '1.72',
  '38.6',
  '57.7%',
  '0.036%'],
 ['140',
  'Armenia',
  '2,952,365',
  '−0.72%',
  '−21,475',
  '104',
  '28,470',
  '−29,013',
  '1.71',
  '36.6',
  '63.8%',
  '0.036%'],
 ['141',
  'Jamaica',
  '2,837,077',
  '−0.07%',
  '−2,098',
  '262',
  '10,830',
  '−11,053',
  '1.34',
  '32.8',
  '60.2%',
  '0.034%'],
 ['142',
  'Lithuania',
  '2,830,144',
  '−1.01%',
  '−28,966',
  '45',
  '62,674',
  '−24,618',
  '1.22',
  '42.3',
  '68.2%',
  '0.034%'],
 ['143',
  'Gambia',
  '2,822,093',
  '2.25%',
  '62,105',
  '279',
  '10,120',
  '−2,984',
  '3.8',
  '18.6',
  '61.3%',
  '0.034%'],
 ['144',
  'Albania',
  '2,771,508',
  '−0.73%',
  '−20,257',
  '101',
  '27,400',
  '−24,230',
  '1.33',
  '37.3',

In [28]:
world_population_country = create_df(table4_data, table4_col_name)
world_population_country.drop('#', inplace=True, axis=1)
world_population_country

,Country (ordependency),Population(2025),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,MedianAge,UrbanPop %,WorldShare
0,India,"1,463,865,525",0.89%,"12,929,734",492,"2,973,190","−495,753",1.94,28.8,37.1%,17.78%
1,China,"1,416,096,094",−0.23%,"−3,225,184",151,"9,388,211","−268,126",1.02,40.1,67.5%,17.20%
2,United States,"347,275,807",0.54%,"1,849,236",38,"9,147,420","1,230,663",1.62,38.5,82.8%,4.22%
3,Indonesia,"285,721,236",0.79%,"2,233,305",158,"1,811,570","−39,509",2.1,30.4,59.6%,3.47%
4,Pakistan,"255,219,554",1.57%,"3,950,390",331,"770,880","−1,235,336",3.5,20.6,34.4%,3.10%
...,...,...,...,...,...,...,...,...,...,...,...
228,Montserrat,"4,359",−0.68%,−30,44,100,−9,1.45,41.6,11.5%,0.000053%
229,Falkland Islands,"3,469",−0.03%,−1,0,"12,170",−17,1.7,42.8,68%,0.000042%
230,Tokelau,"2,608",4.07%,102,261,10,53,2.57,27.3,,0.000032%
231,Niue,"1,821",0.11%,2,7,260,3,2.46,35.7,44.5%,0.000022%
232,Holy See,501,1.01%,5,"1,253",0,13,1,57.4,,0.0000061%

In [33]:
world_population_history.to_csv("extracted_files/world_population_history.csv", index=False)
world_population_forecast.to_csv("extracted_files/world_population_forecast.csv", index=False)
sumary_table.to_csv("extracted_files/sumary_table.csv", index=False)
world_population_Region.to_csv("extracted_files/world_population_Region.csv", index=False)
world_population_country.to_csv("extracted_files/world_population_country.csv", index=False)